## Uticaj predobrade i kvaliteta tekstualnih podataka na performanse klasifikacionih modela: Analiza IMDB recenzija filmova

In [1]:
import numpy as np
import pandas as pd

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

## Učitavanje i osnovni pregled podataka

U ovoj sekciji učitava se skup podataka iz CSV fajla i vrši se osnovni pregled:
- dimenzije skupa podataka,
- nazivi i tipovi kolona,
- primeri redova,
- osnovne statističke karakteristike numeričkih obeležja.

Ovaj korak omogućava bolje razumevanje strukture podataka i identifikaciju potencijalnih problema, kao što su nedostajuće ili nekonzistentne vrednosti.

In [4]:
data_path = "data/IMDB_Dataset.csv"

df = pd.read_csv(data_path)

df = df.dropna(axis=1, how="all")

df.shape

(50000, 2)

In [5]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  str
 1   sentiment  50000 non-null  str
dtypes: str(2)
memory usage: 781.4 KB

In [7]:
df.describe()

                                                   review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [8]:
df.dtypes

review       str
sentiment    str
dtype: object